### ISSUE TITLE
Issues installing elasticsearch

### ISSUE THREAD

**Issue by J-Henry81** [wwalker0307/ElasticMARC#6]
I am working through the setup guide and have run into issues installing Elasticsearch.  Here is what I am running into while trying to install.  Do you know what I am doing wrong or what I am missing?

C:\ElasticMARC\elasticsearch\bin>elasticsearch-service.bat install
future versions of Elasticsearch will require Java 11; your Java version from [C:\Program Files\Java\jdk1.8.0_162\jre] does not meet this requirement
Installing service      :  "elasticsearch-service-x64"
Using JAVA_HOME (64-bit):  "C:\Program Files\Java\jdk1.8.0_162"
Warning: with JDK 8 on Windows, Elasticsearch may be unable to derive correct
  ergonomic settings due to a JDK issue (JDK-8074459). Please use a newer
  version of Java.
Warning: MaxDirectMemorySize may have been miscalculated due to JDK-8074459.
  Please use a newer version of Java or set MaxDirectMemorySize explicitly.
-Des.networkaddress.cache.ttl=60;-Des.networkaddress.cache.negative.ttl=10;-XX:+AlwaysPreTouch;-Xss1m;-Djava.awt.headless=true;-Dfile.encoding=UTF-8;-Djna.nosys=true;-XX:-OmitStackTraceInFastThrow;;-Dio.netty.noUnsafe=true;-Dio.netty.noKeySetOptimization=true;-Dio.netty.recycler.maxCapacityPerThread=0;-Dio.netty.allocator.numDirectArenas=0;-Dlog4j.shutdownHookEnabled=false;-Dlog4j2.disable.jmx=true;-Djava.locale.providers=SPI,JRE;-Xms1g;-Xmx1g;-XX:+UseConcMarkSweepGC;-XX:CMSInitiatingOccupancyFraction=75;-XX:+UseCMSInitiatingOccupancyOnly;-Djava.io.tmpdir=C:\Users\DMARCAdmin\AppData\Local\Temp\2\elasticsearch;-XX:+HeapDumpOnOutOfMemoryError;-XX:HeapDumpPath=data;-XX:ErrorFile=logs/hs_err_pid%p.log;-XX:+PrintGCDetails;-XX:+PrintGCDateStamps;-XX:+PrintTenuringDistribution;-XX:+PrintGCApplicationStoppedTime;-Xloggc:logs/gc.log;-XX:+UseGCLogFileRotation;-XX:NumberOfGCLogFiles=32;-XX:GCLogFileSize=64m;-XX:MaxDirectMemorySize=536870912
Failed installing 'elasticsearch-service-x64' service

**Comment by wwalker0307** [comment]
Looks like you need to utilize a newer version of Java.  If you download the latest version of elasticsearch, you can pull out a supported version of Java JDK to use with Logstash.  If you are using Logstash on the same box as Elasticsearch, set JAVA_HOME to elasticsearch_root\jdk where elasticsearch_root is your elasticsearch directory.

Regardless, your better off asking the question on [Elastic's forums](https://discuss.elastic.co).
