### ISSUE TITLE
Unrecognized VM option 'UseConcMarkSweepGC'

### ISSUE THREAD

**Issue by justgosh** [wwalker0307/ElasticMARC#8]
When running
Root\bin\elasticsearch-service.bat install you will receive the error
Unrecognized VM option 'UseConcMarkSweepGC'
Error: Could not create the Java Virtual Machine.

JDK 15 removed support for the CMS-related flags

ahantoiu commented out 3 lines in the dirtiest possible way and the people rejoiced
https://github.com/elastic/elasticsearch/issues/51361#issuecomment-699655387
#-XX:+UseConcMarkSweepGC
#-XX:CMSInitiatingOccupancyFraction=75
#-XX:+UseCMSInitiatingOccupancyOnly

spinscale used a much more thoughtful approach and the general public fell asleep reading
https://discuss.elastic.co/t/dec-6th-2019-en-understanding-the-jvm-options-file-in-elasticsearch/209949
8-13:-XX:+UseConcMarkSweepGC
8-13:-XX:CMSInitiatingOccupancyFraction=75
8-13:-XX:+UseCMSInitiatingOccupancyOnly

**Comment by wwalker0307** [comment]
This would be an issue specifically with getting Elasticsearch up and running.  I would reference the Elasticsearch documentation for the version of Elasticsearch you are using for the latest installation process.  https://www.elastic.co/guide/en/elasticsearch/reference/index.html

**Comment by justgosh** [comment]
The version of jvm.options in this project does not work with any recent versions of elasticsearch.

When running root\bin\elasticsearch-service.bat with the version of jvm.options found in ElasticMARC/elasticsearch/config/jvm.options
The following error is returned
Unrecognized VM option 'UseConcMarkSweepGC'
Error: Could not create the Java Virtual Machine.

JDK 15 removed support for the CMS-related flags

There are several possible fixes.

Commenting out the lines will avoid errors while the most recent (8.1.1) of jvm.options looks like
8-13:-XX:+UseConcMarkSweepGC
8-13:-XX:CMSInitiatingOccupancyFraction=75
8-13:-XX:+UseCMSInitiatingOccupancyOnly

I'm not not going to fork because I don't know what impact the 2 choices would have on your project.
