### ISSUE TITLE
Kibana.yml variables depreciated

### ISSUE THREAD

**Issue by justgosh** [wwalker0307/ElasticMARC#9]
I believe elasticsearch.url: is now elasticsearch.hosts:

logging.dest:
logging.useUTC: false
logging.silent: false
logging.quiet: false
logging.verbose: false

 may now be
#Enables you to specify a file where Kibana stores log output.
logging.appenders.default:
  type: file
  fileName: /var/logs/kibana.log
  layout:
    type: json

**Comment by wwalker0307** [comment]
I've removed the deprecated logging settings in the kibana yml.  Thanks for the heads up.
